module Emissary

    # stores constants for each turn sequence
    PRODUCTION_FOOD_TRAVEL_LOSS = 0.95
    PRODUCTION_GOODS_TRAVEL_LOSS = 0.95
    FOOD_CONSUMPTION = 0.001
    INDUSTRY_RATE = 0.001
    TRADE_RATE = 0.10
    TRADE_RATE_TRAVEL = 0.01
    START_GOLD_PER_POPULATION = 0.002
    START_GOLD_MAX = 50

end